name: Update README with Version Changes

on:
  push:
    tags:
      - "v*.*.*"  # `vX.Y.Z` のタグが付いたブランチをトリガー

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v4

      - name: 最新のコミット情報を取得
        id: get_commit
        run: |
          LATEST_COMMIT=$(git log -1 --pretty=format:"%s%n%n%b")
          echo "$LATEST_COMMIT" > commit_message.txt
          echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          cat commit_message.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: ChatGPT API で要約・最適化
        id: optimize_commit
        run: |
          COMMIT_MESSAGE=$(echo "${{ env.COMMIT_MESSAGE }}" | jq -Rs .)

          # 日本語での要約を指示
          JSON_PAYLOAD=$(jq -n \
            --arg model "gpt-4" \
            --arg system "あなたは Git のコミットメッセージを日本語で要約する専門家です。" \
            --arg user "以下のコミットメッセージを簡潔なリリースノートに要約してください。\n\n$COMMIT_MESSAGE" \
            '{model: $model, messages: [{role: "system", content: $system}, {role: "user", content: $user}], max_tokens: 200}')

          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            --data "$JSON_PAYLOAD")

          # APIレスポンスをデバッグ
          echo "API RESPONSE: $RESPONSE"

          # ChatGPTのレスポンスから `\n` を削除し、1行に変換
          OPTIMIZED_SUMMARY=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // "要約の生成に失敗しました"' | tr '\n' ' ')

          echo "OPTIMIZED_SUMMARY=$OPTIMIZED_SUMMARY" >> $GITHUB_ENV
  
      - name: README.md にバージョン情報を追加
        run: |
          SUMMARY="${{ env.OPTIMIZED_SUMMARY }}"
          if [ -z "$SUMMARY" ] || [ "$SUMMARY" = "null" ] || [ "$SUMMARY" = "ERROR: No content received" ]; then
            SUMMARY="No summary generated"
          fi

          echo -e "\n## ${{ github.ref_name }}\n\n$SUMMARY" >> README.md
          cat README.md

      - name: README.md の変更をコミット & プッシュ
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # 最新の状態を取得して競合を防ぐ
          git fetch --tags --force
          git pull --rebase origin main || true

          git add README.md
          git commit -m "Update README with release notes for ${{ github.ref_name }}" || exit 0

          # 既存のタグを上書きせず安全にプッシュ
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:main



